### PR TITLE
Safe on application extensions

### PR DESCRIPTION
**Pull request by f-meloni**
👋 ,
I wanted to adopt this really cool library, but I then realised that I needed `APPLICATION_EXTENSION_API_ONLY` true.
It shouldn't generate any problem to the other users, then I then decided to open a PR for it :)

### CODE REVIEW

**Comment by stephencelis** [comment]
:wave: @f-meloni! Thanks for taking the time to submit a PR! We use [XcodeGen](https://www.github.com/yonaskolb/XcodeGen) to automatically generate our Xcode project file. Can you make the changes there instead, and then run `swift run xcodegen` from the root of the repo to regenerate the project file? Here's an example of what needs to be added from another one of our projects: https://github.com/pointfreeco/swift-overture/blob/master/project.yml#L20

**Comment by f-meloni** [comment]
@stephencelis, thank you very much for the review! :)
I already modified the `project.yml`
https://github.com/pointfreeco/swift-nonempty/blob/5668aceed176ae9aac3b8ce0744474cabfebdd58/project.yml#L28
but is really hard to see from the PR diff, because I also re generated the project with XcodeGen, and that made a lot of noise in the diff :)

**Comment by stephencelis** [comment]
Ah, some of the formatting must be due to a newer version of XcodeGen, sorry about that!

**Comment by f-meloni** [comment]
No problem :)

**Pull request merged**
