### PR TITLE
Add generic-backend compatible Coding

### PR DESCRIPTION
**Pull request by jandamm**
Hi there,

I tried to use `NonEmpty` in a type which uses `Codable`.
The first issue was that `Character` is not `Codable` so `NonEmptyString` is not `Codable` either:
```swift
extension NonEmpty: Decodable where C: Decodable, C.Element: Decodable {}
```

`NonEmpty`s current implementation of `Codable` also requires jsons like this `{"head": 1, "tail": [1,2]}`. While this is "safer" you probably won't get it from any server.
To fix this I could write a `MyDataJSONRepresentation` which uses plain `String`s and convert it to the typesafe `MyData` afterwards but then I would have two steps where 'decoding' could go wrong.

I changed the implementation of `NonEmpty+Codable` in a way that is compatible with json like `[1,2,3]`.
The downside is that I had to add two new protocols:
```swift
public protocol NonEmptyDecodable: Decodable, Collection {
	init()
  mutating func append<S>(contentsOf newElements: S) where Element == S.Element, S : Sequence
}

public protocol NonEmptyEncodable: Encodable, Collection {
	init()
	mutating func append<S>(contentsOf newElements: S) where Element == S.Element, S : Sequence
}
```
But it enables you to decode generic json into `NonEmpty` and `NonEmptyString` is also `Codable`.

I'm not 100% sure about the protocols. Another idea was: 
```swift
public protocol NonEmptyDecodable: Decodable, Collection {
	init<S>(_ slice: S) where S : Sequence, S.Element == Element
}

public protocol NonEmptyEncodable: Encodable, Collection {
	init<S>(_ slice: S) where S : Sequence, S.Element == Element
	mutating func append<S>(contentsOf newElements: S) where Element == S.Element, S : Sequence
}
```

Cheers
Jan

### CODE REVIEW

**Comment by stephencelis** [comment]
Hey! Sorry for the radio silence. This PR looks really good. @mbrandonw and I are gonna look it over soon.

**Comment by mbrandonw** [comment]
We finally took a look together! Sorry again for the delay. We're really happy with this but think introducing `append` publicly could be problematic for a library. What do you think about making the protocol requirement namespaced in some way that would avoid collisions? For example, something like `foldFromNonEmpty`?

**Comment by jandamm** [comment]
I named it `append` as it would make adoption easier for some types, but I can see that it may add confusion for types where `append` should not be part of the Type signature.
Now I've added a `static func` requirement.

**Comment by BenLeggiero** [comment]
Now that this is merged, will there be a tagged release for it? Otherwise, SPM won't pick it up

**Comment by stephencelis** [comment]
@BenLeggiero done! https://github.com/pointfreeco/swift-nonempty/releases/tag/0.2.2

**Pull request merged**
