### PR TITLE
Safe on application extensions fix

### PR DESCRIPTION
**Pull request by f-meloni**
I've realised that I made a mistake on https://github.com/pointfreeco/swift-nonempty/pull/16, and I've added the `APPLICATION_EXTENSION_API_ONLY` to the Tests 😅 
This is to fix that.

### CODE REVIEW

**Comment by stephencelis** [comment]
Is this needed for running tests on a device?

**Comment by f-meloni** [comment]
This is needed if you import non-empty in an extension
e.g. an iMessage extension

**Comment by f-meloni** [comment]
Hey @stephencelis did you by any chance get time to have a look at this? :)

**Comment by f-meloni** [comment]
Amazing! Thank you @mbrandonw

**Pull request merged**
